### PR TITLE
Fix towny economy compatability

### LINKED ISSUE #30: Updated Towny support required.
Hello,

As of 0.95.2.13 and onwards the TownyEconomyObject used in Gringott's is no longer available.

If you need help making the change on your end feel free to pop into our [Discord](https://discord.gg/gnpVs5m) or [IRC](http://webchat.esper.net/?channels=towny) and ping me.

### PR DESCRIPTION
**Pull request by ghost**
Towny recently updated its eco methods, this PR fixed Gringotts compatibility with them.

Closes #30

### CODE REVIEW

**Review by writeescape — APPROVED** [review]
this fixes the towny hook, but you need to create another to listen for when a town changes it's name so it updates the signs

**Comment by ghost** [comment]
> this fixes the towny hook, but you need to create another to listen for when a town changes it's name so it updates the signs

Was this working in Gringotts beforehand?

**Comment by nikosgram** [comment]
Hello, I'll do some testings this evening, London Time, with your changes. Just ignore Travis CI, the java version is incorrect.

**Comment by nikosgram** [comment]
@suneettipirneni can you change the version from 2.12 to 2.11.2?

**Comment by ghost** [comment]
@nikosgram yeah for sure

**Pull request merged**
