### PR TITLE
Allow using full ItemMeta for denominations

### LINKED ISSUE #115: Use custom NBT data to determine Money Items.
### **Is your feature request related to a problem? Please describe.**
It would be great if money don't become worthless because you made a typo which you are correcting or you decide to change something in the lore or use another plugin to rename the items to have multilanguage support.
Or if you use another plugin for custom item drops which reformats the name of the item slightly without any viewable difference to the player, it will not be usable as money then.

### **Describe the solution you'd like**
Use a custom NBT tag to save an internal ID which will be set in the config to check its worth so that "old money" keep its value but also can change the name and other options.

### **Describe alternatives you've considered**
I don't really think there is one except to somehow switch the old money with the new one which is annoying for the player depending on the amount of items.

### **Additional context**
🤷‍♂️

### LINKED ISSUE #135: How does NBT data work?
Hello, I am struggling greatly with NBT data and Gringotts, the wiki makes it very vague, I have tried following the documentation but it does not work. In some places, it mentions that a third-party NBT editor is needed, but it is not said how that is to be used. All I want is to change the name of the currency from the actual emerald item to an item named Gems in green. Sorry if this is a dumb question but I can't seem to figure it out, I would really appreciate a point in the right direction, I understand this may not be the correct place for this but I had to ask. Thank you so much!

### LINKED ISSUE #137: Adding Enchants and HideFlags to custom currencies
**Describe the solution you'd like**
I would like to be able to add enchantments to custom currencies in order to get the "glowing" effect from them.  
Beyond this, I would also like to be able to use the HideFlags functionality of vanilla items to hide the enchants of the item.

**Describe alternatives you've considered**
Currently the only other alternative is to simply not have the functionality.  This is definitely a low-priority addition to an already great plugin but I would love to see the functionality added! :)

**Additional context**
Using the below give command you can see that while the item has the enchant glint, the tool tip does not show the echantments.
``/give @p emerald{display:{Name:'{"text":"Gem","color":"green","bold":true}'},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1s}]} 1``

### LINKED ISSUE #138: Load full ItemMeta from config
**Is your feature request related to a problem? Please describe.**
Currently, Gringotts doesn't work well with custom item plugins. Luckily, ItemMeta is ConfigurationSerializable which means that it should be fairly trivial to add things like Enchantments, Flags, HideFlags, etc. to an item. 

Ideally we'd also provide some command to set the denominations in the config based on the current held item so that things like NBT data could be copied over and stored in the internal field of ItemMeta, allowing support for plugins like Oraxen, MythicMobs, and ItemsAdder.

**Describe the solution you'd like**
Update the configuration format to allow for arbitrary ItemMeta.

**Describe alternatives you've considered**
* Add fields to represent each piece of ItemMeta
* Add partial matching so that only the given fields need to match on a given item for it to be considered currency -- I may still do this in my PR just because I think it might be useful.

**Additional context**
I'm going to open a PR for this in the next couple days.

### PR DESCRIPTION
**Pull request by hhenrichsen**
Allow adding full ItemMeta to denominations in the config, and adds a helpful command to put them there (`/gringotts addden 1 Coin Coins`).

Closes #115. 
Closes #135. 
Closes #137. 
Closes #138.

### CODE REVIEW

**Comment by hhenrichsen** [comment]
I have a building version [here](https://github.com/ShatteredSoftware/gringotts/releases/tag/latest) for those who were interested in this feature like I was.

**Comment by hhenrichsen** [comment]
@nikosgram any chance I can get a review on this sometime soon?

**Comment by Isaiah1174** [comment]
Is this version working in 1.19.3? Keep receiving an error when attempting to adddenomination in-game.

`null
org.bukkit.command.CommandException: Unhandled exception executing command 'gringotts' in plugin Gringotts v2.12.4-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-448]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "org.gestern.gringotts.Language.LANG.added_denomination" is null
        at org.gestern.gringotts.commands.GringottsExecutor.onCommand(GringottsExecutor.java:183) ~[gringotts-2.12.4-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]`

**Comment by hhenrichsen** [comment]
@Isaiah-labs Add the same stuff to messages.yml as shows up in the files changed tab of this PR.

**Pull request merged**
