### PR TITLE
Towny: optional vaults number limit & option to force placing vault in town

### PR DESCRIPTION
**Pull request by GroobleDierne**
Together with @PainOchoco, we added some features that integrate with Towny:
- Option `vaults_only_in_towns` to force player to put nations and towns vaults in town claims, it can be any town. Defaults to false.
- Options `max_town_vaults` & `max_nation_vaults` to limit the number of vaults per nations and towns. Defaults to -1 = no limit.
We keep track of the number of vaults via the MetaData API of Towny which allows storing per towns/nations variables.

If you have questions feel free to ping me!

### CODE REVIEW

**Comment by GroobleDierne** [comment]
(This also includes PR #97 )

**Comment by nikosgram** [comment]
Hello, I'm afraid your changes are really old and currently I'm working on modularizing the project to separate the API from the main source. Is it ok if I implement the changes myself and add you credits or I can let you know by the time is ready so you can re-implement the changes?

**Comment by GroobleDierne** [comment]
> Hello, I'm afraid your changes are really old and currently I'm working on modularizing the project to separate the API from the main source. Is it ok if I implement the changes myself and add you credits or I can let you know by the time is ready so you can re-implement the changes?

Feel free to mention PainOchoco or my self when it's ready and we will make another PR

**Comment by nikosgram** [comment]
The modularization has finished. I moved anything relevant to Towny on its own repo/plugin.

https://github.com/nikosgram/gringotts-towny

Relevant thread: https://github.com/nikosgram/gringotts/issues/83

Feel free to include your changes there <3

**Comment by GroobleDierne** [comment]
Ok we will do that in the next weeks 👍

**Pull request closed without merging**
